CREATE TABLE events (
    ID int NOT NULL AUTO_INCREMENT UNIQUE,
    IMAGEDATA MEDIUMBLOB,
    REMIND_DATE TIMESTAMP NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    TITLE VARCHAR(45) NOT NULL,
    INFO VARCHAR (255)
)